### ISSUE TITLE
Doesn't work when used with Redis.Cluster

### ISSUE THREAD

**Issue by mintuhouse** [felixmosh/bull-board#33] opened 2019-10-21 17:07 UTC
`GET /queues`
returns
`{"status":500,"message":"Cannot use 'in' operator to search for 'redis_version' in undefined"}`

when I return `new Redis.Cluster(...)` in `createClient` while creating `Bull.Queue`

**Comment by vcapretz** [comment] 2019-11-10 13:25
hey @mintuhouse, thank's for opening this issue! 

can you provide some more details? Like the node and redis versions you are using? As soon as I get those I can try to reproduce the issue and work on a fix!

**Comment by mintuhouse** [comment] 2019-11-12 07:07
Redis 5.0.6 - elasticache cluster
NodeJS 12.13.0

Let me know if you need anything else

**Comment by vcapretz** [comment] 2020-03-08 22:18
tbh I didn't look into support a cluster setup nor how would that look like, I might need help on this one

we have been using without clusters and it works fine, maybe there are unknown caveats. 😄

**Comment by Heartz66** [comment] 2020-03-08 23:16
A possible scenario I have been thinking of:
worker #1 registers queue to bull-board, but worker #2 hasn't seen the queue yet so it's not registered. reaching bull-board, served by worker #1, once it updates it might reach worker #2 for an update which doesn't know the queue it would like to update in the frontend

**Comment by robbiet480** [comment] 2020-05-20 02:05
FYI bull-board is now working with my cluster on the latest alpha version!

**Comment by felixmosh** [comment] 2021-04-27 15:38
`bull-board` is a "view" over the queues, it should not be part of the queue workers (which supposed to be lean & without any server).

In theory, since `bull-board` is only a "view" over the queues, it doesn't matter if it runs inside a cluster or no, what do I miss?
If someone has any working example which reproduces the problem I would be more the happy to help :]

**Comment by koresar** [comment] 2021-08-09 07:23
I have an example.

1)
start redis cluster: 
```shell
curl -sL https://raw.githubusercontent.com/machinezone/rcc/master/tools/install.sh | sh
rcc make-cluster
```
default port is `30001`.

2)
Create ioredis connection like this:
```js
const connection = new IORedis.Cluster("redis://127.0.0.1:30001");
```

3)
Use the connection above to create BullMQ queue.

4) Try opening the bull-board.
You get exceptions like:
```
All keys in the pipeline should belong to the same slots allocation group
```

The error above is thrown by this `await`:
```js
        const multi = client.multi();
        this.commandByType(types, true, function (key, command) {
            multi[command](key);
        });
        const res = await multi.exec();
```

I have no idea how to fix that.

**Comment by felixmosh** [comment] 2021-08-09 08:13
The code the throws is related to BullMQ, no?

If so, this is not bull-board bug.

**Comment by koresar** [comment] 2021-08-09 09:06
Oh. Right. Indeed. The code I referenced above is in BullMQ's `queue-getters.js` file.

**Comment by felixmosh** [comment] 2022-04-13 06:27
Can we close this issue?

**Comment by koresar** [comment] 2022-05-05 01:17
I think yes.

**Closed** 2022-05-05 04:55 UTC
Labels: bug, help wanted, question
