### ISSUE TITLE
Feature: add failed job as "badge" to list on left

### ISSUE THREAD

**Issue by wootwoot1234** [felixmosh/bull-board#453] opened 2022-09-19 20:19 UTC
Add a badge that shows if there are any failed jobs at a glance.  Maybe something like this:

![image](https://user-images.githubusercontent.com/419609/191108878-cbb7e952-cba7-4a5d-aede-a7820c6c8435.png)

**Comment by felixmosh** [comment] 2022-10-05 07:48
Duplicate of #178
I think that this info on the menu will clutter it with info and therefore should be in the dashboard page #258

**Closed by felixmosh** 2022-10-05 07:48 UTC
