### ISSUE TITLE
Feature: Edit job's data at failed / waiting tabs

### ISSUE THREAD

**Issue by n10000k** [felixmosh/bull-board#478] opened 2022-10-24 13:39 UTC
The ability to edit the "data", save then it creates a log of what it previously was

**Comment by felixmosh** [comment] 2022-10-24 13:51
Can you elaborate?

**Comment by felixmosh** [comment] 2022-10-27 08:18
Duplicate of #425

**Comment by felixmosh** [comment] 2022-10-27 09:51
So it's a duplicate of #426 :]
The ability to add a new job (with predefined params from an existing one).

**Comment by felixmosh** [comment] 2022-10-27 12:27
I don't think that existing jobs is a good practice...
Think that you will need to move it to waiting as well. 

How would you do that with code? is bull & bullmq supports it?

The suggested solution that I thought of, is to add a new job with duplicated data.

**Comment by felixmosh** [comment] 2022-10-27 12:39
Ok, get your point.

**Comment by Jcalcaldev** [comment] 2023-10-17 15:11
Is this currently implemented?

**Comment by felixmosh** [comment] 2023-10-17 16:01
Not yet ...

**Comment by felixmosh** [comment] 2024-09-18 12:15
Released in `v5.22.0`

**Closed** 2024-09-18 12:14 UTC
Labels: enhancement
