### ISSUE TITLE
Bull Board UI stuck on "Loading" 

### ISSUE THREAD

**Issue by whydnxx** [felixmosh/bull-board#378] opened 2022-02-10 16:15 UTC
Hi, we have been looking for something to monitor our Bull Queues for quite some time. and I use Bull Board for monitor queues,
I'm using Fastift rather than Express, and I have been stuck on Loading... This happened only on production, but on development all going well.

![image](https://user-images.githubusercontent.com/50127599/153448305-82deedba-4deb-43a4-a894-861c8301030a.png)
![image](https://user-images.githubusercontent.com/50127599/153448342-b15a4a83-3c4a-41f2-98ad-d9a26ae1c34d.png)

Reproduce:
```ts
export const setupBullBoard = (app: NestFastifyApplication) => {
  const bullServerAdapter = new BullFastifyAdapter();
  bullServerAdapter.setBasePath('/queues/ui');

  const queues = Object.values(QUEUES).map(
    (queue) => new BullAdapter(new Queue(queue)),
  );

  createBullBoard({
    queues,
    serverAdapter: bullServerAdapter,
  });

  app.register(bullServerAdapter.registerPlugin(), {
    prefix: '/queues/ui',
    basePath: '',
  });
};
```

"bull": "^4.2.1"
"@nestjs/core": "^8.2.5"
"@bull-board/fastify": "^3.9.0"

**Comment by felixmosh** [comment] 2022-02-10 16:37
I'm not able to reproduce.
I've used the [with-fastify](https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify) example, and change to you prefixes.
All works.

If it works on dev but not on prod, it is probably a problem of mounting point, can you share the prefix that you have on prod?

**Comment by felixmosh** [comment] 2022-02-12 07:29
Pay attention that you get 504, gateway time out, it is for sure related to your prod setup

**Comment by whydnxx** [comment] 2022-02-12 10:54
yes, on my production server always loading, is my prefix that must use versioning (v1)? but, in development server is going well

**Comment by felixmosh** [comment] 2022-02-12 10:57
can you share you url path (without the domain) of the bull ui & the API requests it made?

**Comment by whydnxx** [comment] 2022-02-12 11:46
endpoint for bull UI is : URL/queues/ui
but I don't understand what API Request you mean
did you mean this?
swagger: /v1/docs/static/index.html
bull ui: /queues/ui
sample: v1/public/...

**Comment by felixmosh** [comment] 2022-02-12 11:47
can you open the console, and check where the UI makes it's api requests?

**Comment by felixmosh** [comment] 2022-02-12 12:02
So routes look OK.
you have probably an issue with reverse-proxy on your prod env.
Do you have one? (a reverse proxy)

**Comment by whydnxx** [comment] 2022-02-12 12:28
No I don't have, and I try to direct using IP and port, it same

**Comment by felixmosh** [comment] 2022-02-12 13:16
It. Is not related to IP.

You don't have nginx or something similar?

**Comment by whydnxx** [comment] 2022-02-12 16:05
finally, I found the thing that makes why it always loads, on my dev, running locally without docker. then I tried to run in my dev workspace using docker. the result is the same as in production, I use Docker in production.

Heres is my docker setup: 
```
version: '2'
services:
  app:
    build: .
    container_name: app-api
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - 8080:8080

  db:
    image: postgres:12
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: just_pay
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql

  redis:
    image: redis:5
    container_name: app-redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgresdata:

```

**Comment by maxime-lenne** [comment] 2022-03-10 15:24
Hi,

I have the same issue with bullboard + fastify on queues that have a large size job payload.

**Comment by felixmosh** [comment] 2022-03-10 15:41
> Hi,
> 
> I have the same issue with bullboard + fastify on queues that have a large size job payload.

It is not related to the this issue.
Can you open a new issue with details (job for example)?

**Comment by jyotirmoy-bst** [comment] 2022-03-30 06:44
I have found the same issue, and it seemed like there was a job with `null` and that was causing an issue for me, so I checked that `node-modules/bull-board/routes/getDataForQeues.js`
In the `getDataForQeues` function, if we use flatMap instead of map.
And in the `formatJob` function, if we use `if (!job) return [];`, then I think this case could be handled, let me know, if this helps.
@felixmosh Can you please do these changes to resolve this issue at least maybe.

**Comment by felixmosh** [comment] 2022-03-30 07:27
Hi @jyotirmoy-bst, looks like you are using a really old version of `bull-board`, can you update to latest and check if it solves your problem?

**Comment by felixmosh** [comment] 2022-05-23 16:25
@whydnxx can we close this issue?

**Closed** 2022-09-06 23:23 UTC
Labels: wontfix

**Comment by fr1sk** [comment] 2023-01-11 12:53
why this is closed?

**Comment by felixmosh** [comment] 2023-01-11 13:02
This issue was stale for 90 days...
What is the error that you get?

**Comment by fr1sk** [comment] 2023-01-11 13:08
Make sense, but I am getting the same error. The same Redis instance on local is working, the deployed version on AWS gives me 504 after some time of loading, this is the only error that I get, nothing on server logs 😢

<img width="1301" alt="CleanShot 2023-01-11 at 14 07 11@2x" src="https://user-images.githubusercontent.com/15851195/211814156-f1364aa2-f2c2-4945-b5a4-e5c69477b15b.png">

**Comment by felixmosh** [comment] 2023-01-11 13:29
Can we debug it somehow?
will you share you screen on Discord?

**Comment by fr1sk** [comment] 2023-01-11 14:56
Unfortunately, I cannot share the code, but let's try to debug it together. My discord username is `defalt#7298`

**Comment by axme100** [comment] 2023-01-26 19:52
@fr1sk Did you ever figure this out? I am having the same problem.

**Comment by felixmosh** [comment] 2023-01-26 19:56
> @fr1sk Did you ever figure this out? I am having the same problem.

What do you get?

**Comment by Aldizh** [comment] 2023-05-30 12:58
Also have the same problem with this one on an AWS instance, works fine locally with default Redis configs. We are getting 504 when requesting `BASE_URL/BASE_BULL_PATH/api/queues?page=1&jobsPerPage=10`.

At first i thought this is related to the reverse proxy issue mentioned earlier by @felixmosh but it is unlikely because a similar route works, i.e: I am able to add a job via `BASE_URL/BASE_BULL_PATH/add?name=PROCESS_SYNC_JOB`

**Comment by kheengz** [comment] 2023-07-17 18:31
While using nestjs
```
import { BullModule } from '@nestjs/bull';
import { ConfigModule, ConfigService } from '@nestjs/config';


BullModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: async (config: ConfigService) => {
        return {
          redis: {
            host: 'your-redis-host',
            port: 'your-redis-port',
            password: 'your-redis-password-if-any',
          },
        };
      },
    }),
```

### Make use of `host`, `port` and/or `password` 
```
host: 'your-redis-host',
port: 'your-redis-port',
password: 'your-redis-password-if-any',
```

### don't use `url`
```
url: `your-redis-url`
```

**Comment by dogukanakkaya** [comment] 2024-08-15 10:12
Why is this closed? Having the same issue with AWS deployment that uses Elasticache instance.

**Comment by felixmosh** [comment] 2024-10-23 07:52
Interesting, I'll investigate it, it should fallback to en automatically... But probably there is some issue.
Can you open a new issue for that?

**Comment by andresjaromezuk** [comment] 2025-03-17 19:42
Hi, I think I'm having the same or a very similar problem.

I have Bullboard configured to view job execution with BullMQ. When I run the server locally and access the /admin/queues URL from the browser, everything works correctly.

However, when the same code is deployed to an Elastic Beanstalk server, and accessing the same URL from the browser, I get the following errors:


/admin/queues/static/css/main.f78ccb06.css:1 
            
            
           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
lib-axios.5b2565a9.js:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
lib-react.067a7e0e.js:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
lib-router.73947a57.js:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
25030.e30fc237.js:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
main.c5ac86f0.js:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
/admin/queues/static/images/logo.svg:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this errorAI
/admin/queues/static/favicon-32x32.png:1 

           Failed to load resource: net::ERR_CONNECTION_REFUSED



**I implemented the following** 

 export const serverAdapter = new ExpressAdapter();
  serverAdapter.setBasePath('/admin/queues');
  
  createBullBoard({
    queues: [
      new BullMQAdapter(notificationQueue), // Only one queue
    ],
    serverAdapter
  });

app.use('/admin/queues', serverAdapter.getRouter())


At the same time, I tried modifying the file

**nginx/conf.d/elasticbeanstalk/00_application.conf**

location / {
    proxy_pass          http://127.0.0.1:8080;
    proxy_http_version  1.1;

    proxy_set_header    Connection          $connection_upgrade;
    proxy_set_header    Upgrade             $http_upgrade;
    proxy_set_header    Host                $host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
}

location /admin/queues/static/ {
    root /var/app/current/node_modules/@bull-board/ui/dist/;
}

to be able to serve static files, but I didn't get any positive results.

Could anyone help me?

Thank you very much.

**Comment by felixmosh** [comment] 2025-03-18 04:30
Do you have these static files on the server? (Inside node_modules)

If so, the express server should server them...check if the paths are correct.

**Comment by gudata** [comment] 2025-12-07 15:29
I have solved this with making zip buffers large and disable enable streaming. 
Here is my working configuration
My setup is bull-board/redis/bullmq running in containers nginx outside of the containers.

```
# Bull Board - bull.website.com and bull.another-website.com
server {
    server_name bull.website.com bull.another-website.com;

    # Disable buffering for SSE/streaming API endpoints
    location ~ ^/api/(queues|redis)/ {
        proxy_pass http://127.0.0.1:3020;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;

        # WebSocket and SSE support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # CRITICAL: Disable buffering for real-time updates
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
        proxy_send_timeout 24h;

        # SSE headers
        proxy_set_header X-Accel-Buffering no;
    }

    # Enable buffering for static files (JS, CSS, images)
    location / {
        proxy_pass http://127.0.0.1:3020;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;

        # WebSocket support (for connection upgrades)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Proxy buffers for large static files (JS bundles)
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 8 256k;
        proxy_busy_buffers_size 256k;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/bull.website.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bull.website.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = bull.another-website.com) {
        return 301 https://$host$request_uri;
    }

    if ($host = bull.website.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name bull.website.com bull.another-website.com;
    return 404;
}

```

Here is what the AI explained 

 1. API Endpoints (lines 6-27) - proxy_buffering off

  For Bull Board's real-time API endpoints (/api/queues/, /api/redis/):
  - ✅ proxy_buffering off - Required for SSE/streaming
  - ✅ proxy_cache off - No caching for real-time data
  - ✅ X-Accel-Buffering no - Tells nginx to not buffer at all
  - ✅ 24h timeouts - Long-lived connections for SSE/WebSocket

  2. Static Files (lines 30-53) - proxy_buffering on

  For JS bundles, CSS, HTML:
  - ✅ proxy_buffering on - Buffers large files completely
  - ✅ 256k buffers - Handles large minified JS files
  - ✅ Normal timeouts - 60s is fine for static content

  Why This Matters for BullMQ

  Bull Board uses two types of connections:

  1. Initial page load → Large JS files → Needs buffering ON (fixes Firefox error)
  2. Real-time updates → SSE or WebSocket → Needs buffering OFF (or updates freeze)

  Without proxy_buffering off for API endpoints:
  - ❌ Queue status won't update in real-time
  - ❌ Job progress bars will freeze
  - ❌ Live metrics won't stream

  Apply the Fix

  Now:
  - ✅ Large JS files will load in Firefox (with compression + buffering)
  - ✅ Real-time updates will work (SSE/WebSocket without buffering)
