### ISSUE TITLE
bull-board not working with AWS serveless 

### ISSUE THREAD

**Issue by GBShadow** [felixmosh/bull-board#485] opened 2022-11-17 13:36 UTC
I have a problem with the bull-board, I created my bull-board application with nest and using AWS Lambda, it works normally, but the bull-board does not, when I access the route only the text "Loading..." appears, but If I start without serverless, the bull-board works normally, does anyone have any idea what it could be?

**Comment by felixmosh** [comment] 2022-11-17 15:37
Hi @GBShadow I think that if you will ask in English, it will approach more ppl.

Anyway, I've translated your message, and looks like you have an issue with Nest & aws serverless, I'm not familiar with this setup, so If someone knows it, I will be more that happy for the help.

**Comment by samuelcole** [comment] 2022-12-14 18:36
This is a duplicate of #444, in my opinion.

bull-board does not work in serverless environments because it uses full paths to load some files.

**Comment by felixmosh** [comment] 2023-02-02 20:33
In serverless env the path to static assets of the ui is not calculated properly,
You can change the path to a the proper value by calling
```js
const uiBasePath = YOUR_CORRECT_VALUE
serverAdapter
  .setViewsPath(path.join(uiBasePath, 'dist'))
  .setStaticPath('/static', path.join(uiBasePath, 'dist/static'));
```
 **after** you pass it to `createBullBoard` function.

Can you try this and let me know if it helped you?

**Comment by samuelcole** [comment] 2023-02-02 21:09
same error, i believe it's throwing on this line:

https://github.com/felixmosh/bull-board/blob/06a1c9828c5c4873172981e60bf85d7d2fc96264/packages/api/src/index.ts#L18

which is executed when running `createBullBoard`

if we could pass a `uiBasePath` to `createBullBoard` instead of it being calculated, that would fix it?

**Comment by felixmosh** [comment] 2023-02-02 22:02
Probably... But i think that serverless is not a good fit anyway, since the board polling its api, you will connect to redis for each request (since serverless env is stateless)
What is the error that you get?

**Comment by samuelcole** [comment] 2023-02-02 22:12
same error as before: https://github.com/felixmosh/bull-board/issues/444#issuecomment-1235734277

**Comment by felixmosh** [comment] 2023-05-16 07:30
@samuelcole, Can you try `v5.2.0` which allows you to pass `uiBasePath` from the outside?

```js
createBullBoard({
    queues: [new BullMQAdapter(exampleBullMq)],
    serverAdapter,
    options: { uiBasePath: 'YOUR_PATH_TO_@bull-board/ui' } // <---
  });
```

**Comment by fabiolnm** [comment] 2023-05-20 06:14
@samuelcole this doesn't seem to work because node_modules isn't included into the resulting Vercel build source.

I also tried https://github.com/vercel/vercel/discussions/4624
```
!node_modules/@bull-board/ui
!node_modules/@bull-board/ui/**
```

and https://github.com/vercel/next.js/discussions/14807
```
// vercel.json
  "functions": {
    "src/pages/api/bull/*": {
      "includeFiles": "node_modules/@bull-board/ui/**"
    }
  }
```

or worse: tried to brute-force include the `node_modules/@bull-board/ui` directory into public (which makes Vercel include it into the build source), but none of these approaches worked, always failing w/ a message similar to:

> Failed to lookup view "index.ejs" in views directory "node_modules/@bull-board/ui/dist"

Let me know if you had any success.

**Closed** 2023-09-03 10:03 UTC
Labels: wontfix

**Comment by AidanHibbard** [comment] 2024-04-17 05:44
For anyone using Nuxt 3, and Vercel who winds up here...

Here's how I got around the issue.

In your `vercel.json` add this (credit to [spb-web](https://github.com/orgs/vercel/discussions/3793#discussioncomment-6851277))

```json
{
  "buildCommand": "nuxt build && cp -R ./node_modules/@bull-board/ui .vercel/output/functions/__nitro.func/node_modules/@bull-board/ui"
}
```

Then in your bull-board config

```ts
options: { uiBasePath: `${process.cwd()}/node_modules/@bull-board/ui`, },
```

I tried for a while to use the includeFiles option in my vercel config, but Nuxt bundles everything into __nitro__ so it wasn't working.
