### ISSUE TITLE
Job details won't show up in express 5.x

### ISSUE THREAD

**Issue by itsTeknas** [felixmosh/bull-board#738] opened 2024-05-09 05:17 UTC
Job Details are not showing up

<img width="1513" alt="Screenshot 2024-05-09 at 10 40 10 AM" src="https://github.com/felixmosh/bull-board/assets/6565602/53fe76c2-7930-4fbf-aa9d-4c95456d31a1">

The list of jobs is working fine

<img width="1513" alt="Screenshot 2024-05-09 at 10 40 16 AM" src="https://github.com/felixmosh/bull-board/assets/6565602/fe4183da-cb44-46cd-bf17-4fc591011b71">

The actual queue is functioning well also.

### My Implementation

```
import { createBullBoard } from '@bull-board/api'
import { BullMQAdapter } from '@bull-board/api/bullMQAdapter'
import { ExpressAdapter } from '@bull-board/express'

import { EmailQueue, PriorityEmailQueue } from '../queues/emailQueue'

const BullMQStatus = new ExpressAdapter()
BullMQStatus.setBasePath('/bullmq')

export const app = express()

app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(express.static(path.join(__dirname, 'public')))
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'hbs')

createBullBoard({
  queues: [
    new BullMQAdapter(EmailQueue, {readOnlyMode: true}),
    new BullMQAdapter(PriorityEmailQueue, {readOnlyMode: true}),
  ],
  serverAdapter: BullMQStatus,
})
app.use('/bullmq', BullMQStatus.getRouter())

```

### Dependencies:
```
"@bull-board/api": "^5.17.1"
"@bull-board/express": "^5.17.1"
"bullmq": "^5.7.5"
```

### Redis 
<img width="553" alt="Screenshot 2024-05-09 at 10 45 59 AM" src="https://github.com/felixmosh/bull-board/assets/6565602/6df3d88f-53fc-4932-a13f-a6f47b6b0b4d">

### Queue Definition
```
import { Queue, Worker } from 'bullmq'

export const PriorityEmailQueue = new Queue<Email>(
  'priority-email-queue',
  {
    connection: redis.duplicate(),
    defaultJobOptions: {
      removeOnComplete: {
        count: 500,
      },
      removeOnFail: {
        count: 500,
      },
    },
  },
)

```

I'm not sure if my implementation is wrong or if this is a bug.

**Comment by felixmosh** [comment] 2024-05-09 05:52
What lib do you use? Bull or BullMQ?

**Comment by itsTeknas** [comment] 2024-05-09 05:56
@felixmosh BullMQ

**Comment by felixmosh** [comment] 2024-05-09 06:04
Ok, your setup looks OK.
Try to check the "latest" tab, or any other. 
Can I debug it somehow?

**Comment by itsTeknas** [comment] 2024-05-09 06:09
Checking the Latest Tab with inspect element,

![Screenshot 2024-05-09 at 11 37 20 AM](https://github.com/felixmosh/bull-board/assets/6565602/781a52fa-4533-416a-bfb3-311e5f84c18b)


```
{
    "queues": [
        {
            "name": "email-queue",
            "statuses": [
                "latest",
                "active",
                "waiting",
                "waiting-children",
                "prioritized",
                "completed",
                "failed",
                "delayed",
                "paused"
            ],
            "counts": {
                "active": 0,
                "completed": 0,
                "delayed": 0,
                "failed": 0,
                "paused": 0,
                "prioritized": 0,
                "waiting": 0,
                "waiting-children": 0
            },
            "jobs": [],
            "pagination": {
                "pageCount": 1,
                "range": {
                    "start": 0,
                    "end": 9
                }
            },
            "readOnlyMode": true,
            "allowRetries": false,
            "allowCompletedRetries": false,
            "isPaused": false
        },
        {
            "name": "priority-email-queue",
            "statuses": [
                "latest",
                "active",
                "waiting",
                "waiting-children",
                "prioritized",
                "completed",
                "failed",
                "delayed",
                "paused"
            ],
            "counts": {
                "active": 0,
                "completed": 2,
                "delayed": 0,
                "failed": 0,
                "paused": 0,
                "prioritized": 0,
                "waiting": 0,
                "waiting-children": 0
            },
            "jobs": [],
            "pagination": {
                "pageCount": 1,
                "range": {
                    "start": 0,
                    "end": 9
                }
            },
            "readOnlyMode": true,
            "allowRetries": false,
            "allowCompletedRetries": false,
            "isPaused": false
        },
        ...
    ]
}
```

The URL is public without any auth, you can check right now

[https://api.core.hedged.online/bullmq](https://api.core.hedged.online/bullmq)

**Comment by itsTeknas** [comment] 2024-05-09 06:23
@felixmosh 
I have a gut feeling that the query parameters may not be parsing.
The response looks the same for the homepage `/bullmq/api/queues?page=1&jobsPerPage=10`

I'm using `"express": "5.0.0-beta.3"`

Middleware stack 

```
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(express.static(path.join(__dirname, 'public')))
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'hbs')
```

**Comment by felixmosh** [comment] 2024-05-09 06:26
Ha, ofcourse, we don't support express 5 yet, can you try to downgrade it to v4?

**Comment by itsTeknas** [comment] 2024-05-09 06:31
Yes, that worked!
But i really use some important express 5 features in my app like `async (req,res)` with throw error in the middle and a global catcher.

I'm afraid, I can't downgrade my project.

Is there any guidance on making it compatible with express 5 ?
Or a quick fix by adding some middleware etc ?

**Comment by felixmosh** [comment] 2024-05-09 06:37
You were right, express 5 probably not parsing query string properly, just add a console.log in side the queue handler, and check what are the params that you get.

**Comment by itsTeknas** [comment] 2024-05-09 06:56
so i did this in express 5.x ,

```
router.use('/bullmq', (req,res,next) => {
  console.log(req.query)
  next()
})
router.use('/bullmq', BullMQStatus.getRouter())

```

### And Got
```
[Object: null prototype] {
  activeQueue: 'priority-email-queue',
  status: 'latest',
  page: '1',
  jobsPerPage: '10'
}
```
when using `app.set('query parser', 'simple')`

### And 

```
 {
  activeQueue: 'priority-email-queue',
  status: 'latest',
  page: '1',
  jobsPerPage: '10'
}
```
when using `app.set('query parser', 'extended')`

Neither of them showed the job details,
As a side-node the rest of my app uses query strings and I never had a problem.

**Comment by felixmosh** [comment] 2024-05-09 07:11
duplicate of #404

**Closed by felixmosh** 2024-05-09 07:11 UTC

**Comment by itsTeknas** [comment] 2024-05-09 07:19
For future readers,
The current workaround is adding a middleware before the express adapter.
```
// BullBoard Currently does not support express 5, so we need to manually set the query as a property on req
router.use('/bullmq', (req: Request, res: Response, next: NextFunction) => {
  const query = req.query;
  // Set query as a property on req instead of as a getter for backward
  // compatibility with express 4
  Object.defineProperty(req, "query", { get: () => query });
  next();
})
router.use('/bullmq', BullMQStatus.getRouter())
```
