### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'm.queues.map') 

### ISSUE THREAD

**Issue by PengWeibin-Mars** [felixmosh/bull-board#345] opened 2021-11-16 06:35 UTC
![image](https://user-images.githubusercontent.com/84702092/141933767-20fd130c-ec2f-4c08-832f-fb68a25a4bd3.png)
This problem occurred after I deployed it on the server
It is normal in the local environment, and the code is the same

**Comment by PengWeibin-Mars** [comment] 2021-11-16 06:37
@felixmosh Do you have any good suggestions

**Comment by PengWeibin-Mars** [comment] 2021-11-16 08:18
const express = require('express')
const { createBullBoard } = require('@bull-board/api')
const { ExpressAdapter } = require('@bull-board/express')
const QueueTool = require('./src/server/queue/queue-tool')

async function run(listenOpts = {}){

  const queues = await QueueTool.getQueues('bull:*:id')

  const serverAdapter = new ExpressAdapter();

  createBullBoard({
    queues,
    serverAdapter:serverAdapter
  })

  const app = express()

  const port = process.env.PORT || 4567;
  const host = listenOpts.host || '0.0.0.0'; // Default: listen to all network interfaces.

  serverAdapter.setBasePath('/ui')
  app.use('/ui', serverAdapter.getRouter());
  app.listen(port, host, () =>{console.log(`Bull-Board is running on port ${port} at hsot ${host}`)})

  return app
  
}

if (require.main === module) run();

module.exports = run;

**Comment by PengWeibin-Mars** [comment] 2021-11-16 08:39
And when I debug locally, the monitoring list is empty. I wonder if it is caused by the empty monitoring list.

**Comment by PengWeibin-Mars** [comment] 2021-11-16 08:40
async function setQueues(pattern){
    const queueNames =  await getQueueNames(pattern)
    const queues = [];
    for (let i = 0; i < queueNames.length; i++) {
        const queue = new Queue(queueNames[i])
        queues.push(new BullAdapter(queue))
    }
    return queues
}

**Comment by PengWeibin-Mars** [comment] 2021-11-16 08:40
The above is the code logic of queues in createBullBoard
Is there a problem with me writing like this

**Comment by PengWeibin-Mars** [comment] 2021-11-16 08:43
![image](https://user-images.githubusercontent.com/84702092/141951892-5239285d-9cdf-4da7-bf71-d6e0ee541a84.png)
There is data in the queue, but it is not updated on the monitoring page

**Comment by PengWeibin-Mars** [comment] 2021-11-16 09:24
[test-monitor.zip](https://github.com/felixmosh/bull-board/files/7545000/test-monitor.zip)
@felixmosh  This is my code logic. It is normal to do this before, but suddenly it is wrong and the monitoring list cannot be displayed.

**Comment by felixmosh** [comment] 2021-11-16 09:52
The code of `setQueues` looks OK to me...

What is the error that you get on the server side?

**Comment by PengWeibin-Mars** [comment] 2021-11-17 05:47
@felixmosh  I found that I will report an error when I use the BullAdapter function
![image](https://user-images.githubusercontent.com/84702092/142141935-c190bf33-9e1c-4d17-8b9a-e2ddb93e8b13.png)
![image](https://user-images.githubusercontent.com/84702092/142142136-6cf2b00c-283a-4631-89d8-67aedbde696e.png)

**Comment by felixmosh** [comment] 2021-11-17 08:05
@PengWeibin-Mars I dont understand from what you write, if the problem is on the server (you posted that the server returns 503) so what is the error on the server?

If there is a server error, the client will throw many errors since it doesn't so resilient.

If you want to chat instantly, you can reach out on twitter @felixmosh, and we will setup an online meeting.

**Comment by PengWeibin-Mars** [comment] 2021-11-24 08:04
Hi @felixmosh  This problem has been solved both locally and on the server
I just add RedisUrl when I initialize the Queue
I don't know why RedisUrl was added suddenly

async function setQueues(pattern){
    const queueNames =  await getQueueNames(pattern)
    const queues = [];
    for (let i = 0; i < queueNames.length; i++) {
        const queue = new Queue(queueNames[i], 'redisurl')
        queues.push(new BullAdapter(queue))
    }
    return queues
}

**Comment by felixmosh** [comment] 2021-11-24 08:27
Glad to hear it solved.
Can we close this?

**Closed** 2021-11-24 08:42 UTC
