### ISSUE TITLE
Hono 4.6.9: Cannot read private member #errorHandler

### ISSUE THREAD

**Issue by smoothdvd** [felixmosh/bull-board#843] opened 2024-11-05 07:21 UTC
```
../../node_modules/.pnpm/hono@4.6.9/node_modules/hono/dist/hono-base.js (91:1) @ eval
 ⨯ TypeError: Cannot read private member #errorHandler from an object whose class did not declare it
    at Array.map (<anonymous>)
    at route (webpack:///src/app/bull-board/[[...index]]/route.ts?c746:27:4)
    at (rsc)/./src/app/bull-board/[[...index]]/route.ts (/Users/alexgao/Dev/dms/apps/api/.next/server/app/bull-board/[[...index]]/route.js:405:1)
```

<img width="963" alt="image" src="https://github.com/user-attachments/assets/d021629f-a858-45a2-b5b5-788471aa2918">

I use hono in nextjs 15 like this
```
const app = new Hono()

// Create the Express adapter
const serverAdapter = new HonoAdapter(serveStatic)

// Create Bull Board with your queues
createBullBoard({
  queues: [
    new BullMQAdapter(getNewspaperArticleEmbedQueue()),
    new BullMQAdapter(getNewspaperPhotoEmbedQueue()),
  ],
  serverAdapter,
})

// Configure the server adapter
serverAdapter.setBasePath('/bull-board')
app.route('/bull-board', serverAdapter.registerPlugin())
```

rollback to hono 4.6.8, there is no issue anymore

**Comment by felixmosh** [comment] 2024-11-05 08:08
Hi, thank you for reporting this issue.
There is no official Next.js support, but if you willing to make a PR that solves this issue, 
I'll more than happy to review it :]

**Comment by stephencoffey** [comment] 2024-11-06 16:50
Not using nextJs, but seeing the same error with 6.3.3 and @hono/node-server.   Pinning hono to 4.6.8 fixes the problem.  Agree with @smoothdvd that it's likely caused by https://github.com/honojs/hono/pull/3596

**Comment by felixmosh** [comment] 2024-11-06 17:27
Hi @stephencoffey can you share a small repo that reproduces the issue? Where is the code that tries to touch Hono's private members?

**Comment by TiBianMod** [comment] 2024-11-09 21:32
the issue is coming from `Hono 4.6.9`

**Comment by TiBianMod** [comment] 2024-11-09 21:57
for the moment pin version `4.6.8`, and you are ready to go.

**Comment by stephencoffey** [comment] 2024-11-11 09:44
> Hi @stephencoffey can you share a small repo that reproduces the issue? Where is the code that tries to touch Hono's private members?

Hi @felixmosh - steps to recreate here:  https://github.com/stephencoffey/bull-board-issue-843-example

**Comment by stephencoffey** [comment] 2024-11-14 09:38
No longer reproducible with hono 4.6.10

**Comment by smoothdvd** [comment] 2024-11-14 13:21
@felixmosh Looks like HonoAdapter.ts is not compatible with the latest hono app:

in hono-base.ts, the errorHandler is #errorHandler now.

```
    app.routes.map((r) => {
      let handler
      if (app.#errorHandler === errorHandler) {
        handler = r.handler
      } else {
        handler = async (c: Context, next: Next) =>
          (await compose<Context>([], app.#errorHandler)(c, () => r.handler(c, next))).res
        ;(handler as any)[COMPOSED_HANDLER] = r.handler
      }

      subApp.#addRoute(r.method, r.path, handler)
    })
```
https://github.com/honojs/hono/blob/082862bb7d8ee95847fbeeb736eb4e20d4646ee7/src/hono-base.ts#L217C1-L218C1

HonoAdapter.ts

```
  setErrorHandler(handler: (error: Error) => ControllerHandlerReturnType): this {
    this.errorHandler = handler;
    return this;
  }
```
This will lead error of "TypeError: Cannot read private member #errorHandler from an object whose class did not declare it" when grouping other HonoAdapter's Hono instance in Honor routes.

```
app.route('/bull-board', serverAdapter.registerPlugin())
```

<img width="485" alt="Screenshot 2024-11-14 at 9 16 49 PM" src="https://github.com/user-attachments/assets/3db6a139-0efa-4ced-a212-a3817ff79751">
<img width="602" alt="Screenshot 2024-11-14 at 9 19 03 PM" src="https://github.com/user-attachments/assets/2c495d8d-e221-42b5-b6ba-caf816e06127">

**Comment by felixmosh** [comment] 2024-11-14 13:30
@smoothdvd please update to Hono 4.6.10 (which solved this issue...)

**Comment by smoothdvd** [comment] 2024-11-14 13:37
@felixmosh I already upgrade to Hono 4.6.10.

**Comment by felixmosh** [comment] 2024-11-14 13:42
I've just tested it locally, with the example (with-hono), with 4.6.9, it fails, with 4.6.10 it works as expected.

**Comment by TiBianMod** [comment] 2024-11-14 16:55
weird stuff....

if you use `require` works, no issue
```ts
const { Hono } = require('hono');
```

if you use `import` throws, some issue
```ts
import { Hono } from "hono";
```
```sh
Cannot access invalid private field (evaluating 'app.#errorHandler')
```

**Comment by felixmosh** [comment] 2024-11-14 17:23
> weird stuff....
> 
> if you use `require` works, no issue
> 
> ```ts
> const { Hono } = require('hono');
> ```
> 
> if you use `import` throws, some issue
> 
> ```ts
> import { Hono } from "hono";
> ```
> 
> ```shell
> Cannot access invalid private field (evaluating 'app.#errorHandler')
> ```

Actually it is not weird, since Node applies the private field validation on ESM only

**Comment by TiBianMod** [comment] 2024-11-14 17:57
OK, but this is an issue that we need to solve @felixmosh 
I think you need to reopen the issue!!!

**Comment by felixmosh** [comment] 2024-11-14 18:06
We should use `onError` instead...
Will you open a PR

**Comment by felixmosh** [comment] 2024-11-19 09:19
I've tested the code, looks like this is related to Hono,
![image](https://github.com/user-attachments/assets/d59b0262-7c82-4aa3-9711-52e7cb505279)

When using the pattern of `app.route('/', new Hono())`, the code above, tries to access a private property of the second Hono instance. which is wrong.

**Comment by TiBianMod** [comment] 2024-11-20 03:28
@felixmosh the issue is solved on `Hone v4.6.11`

PR: https://github.com/honojs/hono/pull/3692
Relase: https://github.com/honojs/hono/releases/tag/v4.6.11

**Comment by felixmosh** [comment] 2024-11-20 09:44
Can we close this issue?

**Closed** 2024-11-20 10:29 UTC

**Comment by yusukebe** [comment] 2024-11-20 12:35
Sorry for the trouble!
